### PR TITLE
Introducting new variable GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT 

### LINKED ISSUE #45: GITHUB_SHA different value for PR events
**Is your feature request related to a problem? Please describe.**

Actually, GitHub is changing the value of `GITHUB_SHA` for pull request events that refers to _the last merge commit on the `GITHUB_REF` branch_. At first, I would expect that it refers to the last commit of the branch. I wanted to use this behaviour for tagging container images build from PR events.

`github-slug-action` **is actually working as intended.**

**Describe the solution you'd like**

I would like to have a way of telling `github-slug-action` that I want to get the value of the last commit of my branch instead the logic used by GitHub.

Here's some track to get us started:
- https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286/2
- https://github.community/t/github-sha-but-how-to-get-the-latest-commit-reference-on-a-branch/17160

I did not try those solutions yet.

**Describe alternatives you've considered**

/

**Additional context**

/

WDYT?

### PR DESCRIPTION
**Pull request by MadJlzz**
PR solves #45 

@rlespinasse 

I had some hard time testing to be honnest (and I am still not sure the right way to test that unless running the action directly on GitHub)

I added 2 dependencies:
- `@actions/github` is used to get the context of why an action was triggered
- `@octokit/webhooks` to get the typings for `WebhookPayloadPullRequest`

Sadly, all typings are not present in `@action/core` 😭 
There is a reference to add it to the toolkit library for action [here](https://github.com/actions/toolkit/issues/147).

For linting errors, I let you tell me which tool you are using for that so that I can fix any errors that will surely show up in the pipeline. (and I will add that in `DEVELOPERS.md` as well 😀)

### CODE REVIEW

**Comment by rlespinasse** [comment]
Hello, I think you can simplify this by using `eventData.hasOwnProperty('pull_request')` like for GITHUB_EVENT_REF_SLUG. This will enable the support of all type of events who contains an `pull_request` object.

**Comment by MadJlzz** [comment]
Indeed. I am so bad with JavaScript, sorry about that 😬

**Comment by rlespinasse** [comment]
No need to be sorry about that, me too i'm not fluent in Javascript.
Can you rebase your branch on top of the default branch, I just commit a fix in the Linter configuration.

**Comment by MadJlzz** [comment]
I may have messed up with the rebase. I made a clean branch `feat/github_sha_pr_event_2`. Weird enough, I cannot change the branch comparison from this PR. Can you check ?

**Comment by rlespinasse** [comment]
@MadJlzz I can't change the branch in your PR. You can fix the `feat/github_sha_pr_event` branch with the following commands

```
$ git checkout feat/github_sha_pr_event
$ git reset --hard feat/github_sha_pr_event_2
$ git push --force origin feat/github_sha_pr_event
```

**Comment by MadJlzz** [comment]
@rlespinasse done! Don't know why but the linting still fails. Even some piece that I didn't touch

**Comment by rlespinasse** [comment]
Since we use Prettier as formatter, the linter need more configuration to correctly manage this. I will merge this PR.

**Review by rlespinasse — APPROVED** [review]

**Pull request merged**
